// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAflanbyFgcATbqjb_LZA-mA_s6ad0YiQg',
    appId: '1:688614320745:web:05b6b53ae817d7278fd0f8',
    messagingSenderId: '688614320745',
    projectId: 'fcm-flood-monitoring',
    authDomain: 'fcm-flood-monitoring.firebaseapp.com',
    storageBucket: 'fcm-flood-monitoring.firebasestorage.app',
    measurementId: 'G-2WE22J9Z28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHFfkof6uGWM6CYH3NX-jfhK4sYF7i0DA',
    appId: '1:688614320745:android:b6f42681323bde9d8fd0f8',
    messagingSenderId: '688614320745',
    projectId: 'fcm-flood-monitoring',
    storageBucket: 'fcm-flood-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZuveJCe6y-WENY8KsrebVo5RPVVmXXRo',
    appId: '1:688614320745:ios:df1b7736e579d87e8fd0f8',
    messagingSenderId: '688614320745',
    projectId: 'fcm-flood-monitoring',
    storageBucket: 'fcm-flood-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZuveJCe6y-WENY8KsrebVo5RPVVmXXRo',
    appId: '1:688614320745:ios:df1b7736e579d87e8fd0f8',
    messagingSenderId: '688614320745',
    projectId: 'fcm-flood-monitoring',
    storageBucket: 'fcm-flood-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAflanbyFgcATbqjb_LZA-mA_s6ad0YiQg',
    appId: '1:688614320745:web:54c02dbb503b64d68fd0f8',
    messagingSenderId: '688614320745',
    projectId: 'fcm-flood-monitoring',
    authDomain: 'fcm-flood-monitoring.firebaseapp.com',
    storageBucket: 'fcm-flood-monitoring.firebasestorage.app',
    measurementId: 'G-M3N6E9E0XS',
  );
}
